DELETE FROM CONTRACTOR_TYPE
INSERT INTO CONTRACTOR_TYPE ( ID, CT_NAME ) VALUES ( 1, N'Физическо лице' )
INSERT INTO CONTRACTOR_TYPE ( ID, CT_NAME ) VALUES ( 2, N'Юридическо лице' )

DELETE FROM DISCOUNT_KIND
INSERT INTO DISCOUNT_KIND ( ID, DK_NAME ) VALUES ( 1, N'за всички стоки' )
INSERT INTO DISCOUNT_KIND ( ID, DK_NAME ) VALUES ( 2, N'само за група' )
INSERT INTO DISCOUNT_KIND ( ID, DK_NAME ) VALUES ( 3, N'само за стока' )