USE [db48acc9c4eec24cc6bb96a4d000858d2d]
GO

/****** Object:  Table [dbo].[CONTRACTOR_COMPANY]    Script Date: 9.8.2015 г. 16:03:39 ч. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONTRACTOR_COMPANY](
	[CONTRACTOR_ID] [int] NOT NULL,
	[ACCOUNTABLE_PERSON] [nvarchar](256) NULL,
 CONSTRAINT [PK_CONTRACTOR_COMPANY] PRIMARY KEY CLUSTERED 
(
	[CONTRACTOR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CONTRACTOR_COMPANY]  WITH CHECK ADD  CONSTRAINT [FK_CONTRACTOR_COMPANY_CONTRACTOR] FOREIGN KEY([CONTRACTOR_ID])
REFERENCES [dbo].[CONTRACTOR] ([ID])
GO

ALTER TABLE [dbo].[CONTRACTOR_COMPANY] CHECK CONSTRAINT [FK_CONTRACTOR_COMPANY_CONTRACTOR]
GO

