USE [db48acc9c4eec24cc6bb96a4d000858d2d]
GO

/****** Object:  Table [dbo].[DISCOUNT_KIND]    Script Date: 30.7.2015 ã. 16:14:58 ÷. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DISCOUNT_KIND](
	[ID] [int] NOT NULL,
	[DK_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DISCOUNT_KIND] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


