USE [db48acc9c4eec24cc6bb96a4d000858d2d]
GO

/****** Object:  Table [dbo].[DISCOUNT]    Script Date: 30.7.2015 г. 21:09:31 ч. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DISCOUNT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[D_NAME] [nvarchar](256) NOT NULL,
	[VALID_FROM_DATE] [datetime] NULL,
	[VALID_TO_DATE] [nvarchar](50) NULL,
	[DISCOUNT_KIND_ID] [int] NULL,
	[D_VALUE] [money] NULL,
 CONSTRAINT [PK_DISCOUNT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

