USE [db48acc9c4eec24cc6bb96a4d000858d2d]
GO

/****** Object:  Table [dbo].[DISCOUNT_GROUP]    Script Date: 6.8.2015 г. 22:14:50 ч. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DISCOUNT_GROUP](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DG_NAME] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_DISCOUNT_GROUP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

